sudo: required
services:
- docker
addons:
  apt:
    packages:
      - docker-ce
language: bash
script:
  - bash build.sh

  # tag the image
  - docker image tag ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} ${DOCKER_IMAGE_NAME}:latest
  # push image
  - >
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}"
      docker push ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
      docker push ${DOCKER_IMAGE_NAME}:latest
    fi
