# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source

version: '3.3'

networks:
  backend:

volumes:
  dspace: {}
  postgres: {}

services:
  postgres:
    image: postgres:9.6.2
    networks:
      backend:
    volumes:
      - postgres:/var/lib/postgresql/data

  dspace:
    image: 4science/dspace-cris:cris-5.8.0
#    build:
#      context: ./
#      dockerfile: Dockerfile
# Add meta information to the image
#      args:
# Specify the base repository 
#        - DSPACE_VERSION=""
#        - DSPACE_VCS_URL=""
#        - DSPACE_VCS_REF=""
# Specify the repository with custom changes
#        - MODS_VERSION=""
#        - MODS_VCS_URL=""
#        - MODS_VCS_REF=""
#        - BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
#        - VCS_REF="${TRAVIS_COMMIT}"
#        - VERSION="${TRAVIS_TAG}"

    networks:
      backend:
    environment:
      POSTGRES_DB_HOST: postgres
      DSPACE_WEBAPPS: "jspui xmlui rest oai rdf sword swordv2"
      CATALINA_OPTS: "-Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true -Xmx2048m -Xms2048m -XX:MaxPermSize=512m"
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWD: admin123
      # ADMIN_FIRSTNAME: DSpace
      # ADMIN_LASTNAME: Admin
      # ADMIN_LANGUAGE: en
    depends_on:
      - postgres
    volumes:
      - dspace:/dspace
    ports:
      - "8080:8080"
